# Ref. https://swagger.io/specification/
openapi: '3.0.3'
info:
  title: 'Runner Talk Chat'
  version: 'automatically set by codes'
paths:
  '/api/v1/chat/rooms/{roomId}':
    get:
      tags:
        - ChatRoom
      parameters:
        - name: roomId
          required: true
          in: path
          schema:
            type: string
      responses:
        200:
          description: 'returns the chat room information'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoom'
        404:
          description: 'the chat room does not exist'
    delete:
      tags:
        - ChatRoom
      parameters:
        - name: roomId
          required: true
          in: path
          schema:
            type: string
      responses:
        200:
          description: 'delete the chat room information'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoom'
        404:
          description: 'the chat room does not exist'
  '/api/v1/chat/rooms':
    get:
      tags:
        - ChatRoom
      responses:
        200:
          description: 'returns the chat room information list'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoom'
    post:
      tags:
        - ChatRoom
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRoom'
      responses:
        201:
          description: 'create the chat room information'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoom'
    put:
      tags:
        - ChatRoom
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRoom'
      responses:
        200:
          description: 'returns the chat room information'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoom'
        404:
          description: 'the student does not exist'
components:
  schemas:
    ChatRoom:
      type: object
      properties:
        id:
          type: string
          example: 'room1'
          readOnly: true
        name:
          type: string
          example: 'chat room name'
        description:
          type: string
          example: 'chat room description'
        creatorId:
          type: string
          example: 'user1'
          readOnly: true
        participants:
          type: array
          items:
            type: string
          example: ['user1', 'user2']
        lastMessage:
          type: object
          properties:
            content:
              type: string
              example: 'message content'
            timestamp:
              type: string
              format: date-time
              example: '2022-03-04T12:34:56.789Z'
        createdAt:
          type: string
          format: date-time
          example: '2022-03-04T12:34:56.789Z'
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          example: '2022-03-04T12:34:56.789Z'
          readOnly: true
tags:
  - name: ChatRoom
